// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwvlj46ey_TFADWlD-HWeNrmLBJlL27SI',
    appId: '1:378267874629:web:39857ffb0580b577497a2c',
    messagingSenderId: '378267874629',
    projectId: 'presisawit-app',
    authDomain: 'presisawit-app.firebaseapp.com',
    storageBucket: 'presisawit-app.appspot.com',
    measurementId: 'G-LV31DQ2NF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwNLNfPv4YUIYaFDfK5phROME3Nje2PFs',
    appId: '1:378267874629:android:3425369907841f7c497a2c',
    messagingSenderId: '378267874629',
    projectId: 'presisawit-app',
    storageBucket: 'presisawit-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_LA8m3eTsETq4uzLWqXJoq9FUkpdcovQ',
    appId: '1:378267874629:ios:ac2d470ccbbc3138497a2c',
    messagingSenderId: '378267874629',
    projectId: 'presisawit-app',
    storageBucket: 'presisawit-app.appspot.com',
    iosClientId: '378267874629-kh00ppmvm6gdqsd4q6h9pobbr6s9iv72.apps.googleusercontent.com',
    iosBundleId: 'com.example.presisawitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_LA8m3eTsETq4uzLWqXJoq9FUkpdcovQ',
    appId: '1:378267874629:ios:ac2d470ccbbc3138497a2c',
    messagingSenderId: '378267874629',
    projectId: 'presisawit-app',
    storageBucket: 'presisawit-app.appspot.com',
    iosClientId: '378267874629-kh00ppmvm6gdqsd4q6h9pobbr6s9iv72.apps.googleusercontent.com',
    iosBundleId: 'com.example.presisawitApp',
  );
}
